// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using exam2.Data;

#nullable disable

namespace exam2.Migrations
{
    [DbContext(typeof(RailwayDbContext))]
    [Migration("20240714195911_RemovedIndexes")]
    partial class RemovedIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("exam2.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 7, 14, 22, 59, 11, 440, DateTimeKind.Local).AddTicks(6629),
                            Latitude = 50.450099999999999,
                            Longitude = 30.523399999999999,
                            Name = "Kyiv",
                            UpdatedAt = new DateTime(2024, 7, 14, 22, 59, 11, 440, DateTimeKind.Local).AddTicks(6705)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 7, 14, 22, 59, 11, 440, DateTimeKind.Local).AddTicks(6713),
                            Latitude = 49.839700000000001,
                            Longitude = 24.029699999999998,
                            Name = "Lviv",
                            UpdatedAt = new DateTime(2024, 7, 14, 22, 59, 11, 440, DateTimeKind.Local).AddTicks(6716)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 7, 14, 22, 59, 11, 440, DateTimeKind.Local).AddTicks(6721),
                            Latitude = 46.482500000000002,
                            Longitude = 30.723299999999998,
                            Name = "Odesa",
                            UpdatedAt = new DateTime(2024, 7, 14, 22, 59, 11, 440, DateTimeKind.Local).AddTicks(6724)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 7, 14, 22, 59, 11, 440, DateTimeKind.Local).AddTicks(6729),
                            Latitude = 48.464700000000001,
                            Longitude = 35.046199999999999,
                            Name = "Dnipro",
                            UpdatedAt = new DateTime(2024, 7, 14, 22, 59, 11, 440, DateTimeKind.Local).AddTicks(6731)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 7, 14, 22, 59, 11, 440, DateTimeKind.Local).AddTicks(6736),
                            Latitude = 49.993499999999997,
                            Longitude = 36.230400000000003,
                            Name = "Kharkiv",
                            UpdatedAt = new DateTime(2024, 7, 14, 22, 59, 11, 440, DateTimeKind.Local).AddTicks(6739)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 7, 14, 22, 59, 11, 440, DateTimeKind.Local).AddTicks(6744),
                            Latitude = 47.838799999999999,
                            Longitude = 35.139600000000002,
                            Name = "Zaporizhzhia",
                            UpdatedAt = new DateTime(2024, 7, 14, 22, 59, 11, 440, DateTimeKind.Local).AddTicks(6747)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 7, 14, 22, 59, 11, 440, DateTimeKind.Local).AddTicks(6752),
                            Latitude = 46.975000000000001,
                            Longitude = 31.994599999999998,
                            Name = "Mykolaiv",
                            UpdatedAt = new DateTime(2024, 7, 14, 22, 59, 11, 440, DateTimeKind.Local).AddTicks(6755)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 7, 14, 22, 59, 11, 440, DateTimeKind.Local).AddTicks(6759),
                            Latitude = 49.2331,
                            Longitude = 28.4682,
                            Name = "Vinnytsia",
                            UpdatedAt = new DateTime(2024, 7, 14, 22, 59, 11, 440, DateTimeKind.Local).AddTicks(6762)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 7, 14, 22, 59, 11, 440, DateTimeKind.Local).AddTicks(6767),
                            Latitude = 49.588299999999997,
                            Longitude = 34.551400000000001,
                            Name = "Poltava",
                            UpdatedAt = new DateTime(2024, 7, 14, 22, 59, 11, 440, DateTimeKind.Local).AddTicks(6770)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 7, 14, 22, 59, 11, 440, DateTimeKind.Local).AddTicks(6774),
                            Latitude = 51.498199999999997,
                            Longitude = 31.289300000000001,
                            Name = "Chernihiv",
                            UpdatedAt = new DateTime(2024, 7, 14, 22, 59, 11, 440, DateTimeKind.Local).AddTicks(6777)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 7, 14, 22, 59, 11, 440, DateTimeKind.Local).AddTicks(6782),
                            Latitude = 48.290799999999997,
                            Longitude = 25.9345,
                            Name = "Chernivtsi",
                            UpdatedAt = new DateTime(2024, 7, 14, 22, 59, 11, 440, DateTimeKind.Local).AddTicks(6784)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 7, 14, 22, 59, 11, 440, DateTimeKind.Local).AddTicks(6789),
                            Latitude = 46.635399999999997,
                            Longitude = 32.616900000000001,
                            Name = "Kherson",
                            UpdatedAt = new DateTime(2024, 7, 14, 22, 59, 11, 440, DateTimeKind.Local).AddTicks(6792)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2024, 7, 14, 22, 59, 11, 440, DateTimeKind.Local).AddTicks(6827),
                            Latitude = 48.922600000000003,
                            Longitude = 24.7103,
                            Name = "Ivano-Frankivsk",
                            UpdatedAt = new DateTime(2024, 7, 14, 22, 59, 11, 440, DateTimeKind.Local).AddTicks(6832)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2024, 7, 14, 22, 59, 11, 440, DateTimeKind.Local).AddTicks(6837),
                            Latitude = 50.907699999999998,
                            Longitude = 34.798099999999998,
                            Name = "Sumy",
                            UpdatedAt = new DateTime(2024, 7, 14, 22, 59, 11, 440, DateTimeKind.Local).AddTicks(6841)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2024, 7, 14, 22, 59, 11, 440, DateTimeKind.Local).AddTicks(6847),
                            Latitude = 49.5535,
                            Longitude = 25.594799999999999,
                            Name = "Ternopil",
                            UpdatedAt = new DateTime(2024, 7, 14, 22, 59, 11, 440, DateTimeKind.Local).AddTicks(6852)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2024, 7, 14, 22, 59, 11, 440, DateTimeKind.Local).AddTicks(6858),
                            Latitude = 48.620800000000003,
                            Longitude = 22.2879,
                            Name = "Uzhhorod",
                            UpdatedAt = new DateTime(2024, 7, 14, 22, 59, 11, 440, DateTimeKind.Local).AddTicks(6863)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2024, 7, 14, 22, 59, 11, 440, DateTimeKind.Local).AddTicks(6869),
                            Latitude = 50.264899999999997,
                            Longitude = 28.6767,
                            Name = "Zhytomyr",
                            UpdatedAt = new DateTime(2024, 7, 14, 22, 59, 11, 440, DateTimeKind.Local).AddTicks(6873)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2024, 7, 14, 22, 59, 11, 440, DateTimeKind.Local).AddTicks(6879),
                            Latitude = 50.619900000000001,
                            Longitude = 26.2516,
                            Name = "Rivne",
                            UpdatedAt = new DateTime(2024, 7, 14, 22, 59, 11, 440, DateTimeKind.Local).AddTicks(6883)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2024, 7, 14, 22, 59, 11, 440, DateTimeKind.Local).AddTicks(6888),
                            Latitude = 50.747199999999999,
                            Longitude = 25.325399999999998,
                            Name = "Lutsk",
                            UpdatedAt = new DateTime(2024, 7, 14, 22, 59, 11, 440, DateTimeKind.Local).AddTicks(6892)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2024, 7, 14, 22, 59, 11, 440, DateTimeKind.Local).AddTicks(6897),
                            Latitude = 48.507899999999999,
                            Longitude = 32.262300000000003,
                            Name = "Kropyvnytskyi",
                            UpdatedAt = new DateTime(2024, 7, 14, 22, 59, 11, 440, DateTimeKind.Local).AddTicks(6901)
                        });
                });

            modelBuilder.Entity("exam2.Entities.Journey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityArrivalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityDepartureId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DispatchAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityArrivalId");

                    b.HasIndex("CityDepartureId");

                    b.ToTable("Journeys");
                });

            modelBuilder.Entity("exam2.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPurchased")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JourneyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Place")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JourneyId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("exam2.Entities.Journey", b =>
                {
                    b.HasOne("exam2.Entities.City", "CityArrival")
                        .WithMany("JourneysArriving")
                        .HasForeignKey("CityArrivalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("exam2.Entities.City", "CityDeparture")
                        .WithMany("JourneysDeparting")
                        .HasForeignKey("CityDepartureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CityArrival");

                    b.Navigation("CityDeparture");
                });

            modelBuilder.Entity("exam2.Entities.Ticket", b =>
                {
                    b.HasOne("exam2.Entities.Journey", "Journey")
                        .WithMany("Tickets")
                        .HasForeignKey("JourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Journey");
                });

            modelBuilder.Entity("exam2.Entities.City", b =>
                {
                    b.Navigation("JourneysArriving");

                    b.Navigation("JourneysDeparting");
                });

            modelBuilder.Entity("exam2.Entities.Journey", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
